# dev profile
server:
  port: 9100

spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true

  # H2
  datasource:
    url: jdbc:h2:mem:chokchokdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  # Hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
