# prod profile
server:
  port: 8100

spring:
  config:
    activate:
      on-profile: prod

    import: optional:file:.env[.properties]

  # MySQL
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    # HikariCP 설정
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000  # 10분
      max-lifetime: 1800000 # 30분
      connection-timeout: 30000 # 30초
      pool-name: HikariChokChokPool

  # Hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


