### 1. 회원가입
POST http://localhost:9200/api/members
Content-Type: application/json

{
  "username": "test",
  "email": "test@example.com",
  "password": "securePassword123!",
  "dateOfBirth": "1999-09-09",
  "gender": "남성"
}

### 2. 회원 정보 조회
GET http://localhost:9200/api/members/info
X-MEMBER-ID: 708585662456099981
X-MEMBER-ROLES: ROLE_USER


### 3. 로그인 정보 조회
GET http://localhost:9200/api/members/login/test@example.com
