### 1. 회원가입
POST http://localhost:9200/api/members
Content-Type: application/json

{
  "username": "test",
  "email": "test@example.com",
  "password": "securePassword123!",
  "dateOfBirth": "1999-09-09",
  "gender": "남성"
}

### 2. 회원 정보 조회
GET http://localhost:9200/api/members/info
X-MEMBER-ID: 717319487602459715
X-MEMBER-ROLES: ROLE_USER


### 3. 로그인 정보 조회
GET http://localhost:9200/api/members/login/test@example.com

### 카테고리 등록 - 부모
POST http://localhost:9200/api/admin/categories
X-MEMBER-ID: 717324517151355893
X-MEMBER-ROLES: ROLE_ADMIN
Content-Type: application/json

{
  "name": "스킨케어",
  "parentId": null
}

### 카테고리 등록 - 부모의 자식
POST http://localhost:9200/api/admin/categories
X-MEMBER-ID: 717324517151355893
X-MEMBER-ROLES: ROLE_ADMIN
Content-Type: application/json

{
  "name": "스킨",
  "parentId": 1
}

### 카테고리 조회 - 전체
GET http://localhost:9200/api/categories/all

### 카테고리 조회 - 단일 - 부모
GET http://localhost:9200/api/categories/1

### 카테고리 조회 - 단일 - 자식
GET http://localhost:9200/api/categories/2

### 카테고리 수정 - 이름
PUT http://localhost:9200/api/admin/categories/2/name?name=크림
X-MEMBER-ID: 717292834485478576
X-MEMBER-ROLES: ROLE_ADMIN

### 카테고리 수정 - 부모
PUT http://localhost:9200/api/admin/categories/2/order
X-MEMBER-ID: 717292834485478576
X-MEMBER-ROLES: ROLE_ADMIN
Content-Type: application/json

{
  "name": "크림",
  "parentId": null
}
